<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sony" ignored="2" name="CreateCustomerAPITest" tests="4" failures="1" timestamp="14 Oct 2021 18:00:36 GMT" time="17.979" errors="0">
  <testcase name="validateCreateCustomerAPIWithInvalidSecretKey" time="11.948" classname="testCases.CreateCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at testCases.CreateCustomerTest.validateCreateCustomerAPIWithInvalidSecretKey(CreateCustomerTest.java:62)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInvalidSecretKey -->
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="4.65" classname="testCases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="4.656" classname="testCases.CreateCustomerTest"/>
  <testcase name="validateCreateCustomerAPIWithValidSecretKey" time="4.69" classname="testCases.CreateCustomerTest"/>
  <testcase name="@BeforeSuite setUp" time="0.0" classname="setUp.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="setUp.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
</testsuite> <!-- CreateCustomerAPITest -->
