<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sony" ignored="2" name="DeleteCustomerAPITest" tests="1" failures="1" timestamp="14 Oct 2021 18:00:32 GMT" time="13.011" errors="0">
  <testcase name="validateDeleteCustomerAPIWithValidCustomerID" time="11.95" classname="testCases.DeleteCustomerTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at testCases.DeleteCustomerTest.validateDeleteCustomerAPIWithValidCustomerID(DeleteCustomerTest.java:29)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateDeleteCustomerAPIWithValidCustomerID -->
  <testcase name="@BeforeSuite setUp" time="0.0" classname="setUp.BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite setUp -->
  <testcase name="@AfterSuite tearDown" time="0.0" classname="setUp.BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
</testsuite> <!-- DeleteCustomerAPITest -->
